name: Deploy to WordPress SVN

on:
  push:
    branches:
      - main  # 트리거할 브랜치 (예: main)

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: WordPress-SVN-Deploy

    steps:
    - name: Checkout Git repository
      uses: actions/checkout@v3

    - name: Setup Subversion
      run: sudo apt-get install subversion

    - name: Checkout SVN repository (trunk only)
      run: |
        svn checkout https://plugins.svn.wordpress.org/kilho-simple-avatar/trunk --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }} --non-interactive svn/trunk
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}

    - name: Extract stable tag from readme.txt
      id: get_stable_tag
      run: |
        stable_tag=$(grep -i "Stable tag:" readme.txt | awk '{print $3}')
        echo "Stable tag is $stable_tag"
        echo "stable_tag=$stable_tag" >> $GITHUB_ENV

    - name: Check if tag exists
      run: |
        stable_tag=${{ env.stable_tag }}
        if svn list https://plugins.svn.wordpress.org/kilho-simple-avatar/tags/$stable_tag --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }} --non-interactive; then
          echo "Tag $stable_tag already exists. Skipping tag creation."
          exit 0
        fi

    - name: Create new tag directory if it doesn't exist
      run: |
        stable_tag=${{ env.stable_tag }}
        if ! svn list https://plugins.svn.wordpress.org/kilho-simple-avatar/tags/$stable_tag --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }} --non-interactive; then
          svn cp svn/trunk https://plugins.svn.wordpress.org/kilho-simple-avatar/tags/$stable_tag --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }} --non-interactive
          svn commit -m "Tagging version $stable_tag" https://plugins.svn.wordpress.org/kilho-simple-avatar/tags/$stable_tag --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }} --non-interactive
        else
          echo "Tag $stable_tag already exists. Skipping tag creation."
        fi
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
