name: Deploy to WordPress SVN

on:
  push:
    branches:
      - main  # 트리거할 브랜치 (예: main)

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: WordPress-SVN-Deploy

    steps:
    - name: Checkout Git repository
      uses: actions/checkout@v3

    - name: Setup Subversion
      run: sudo apt-get install subversion

    - name: Checkout SVN repository
      run: |
        svn checkout https://plugins.svn.wordpress.org/kilho-simple-avatar/ --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }} --non-interactive svn
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}

    - name: Extract stable tag from readme.txt
      id: get_stable_tag
      run: |
        stable_tag=$(grep -i "Stable tag:" readme.txt | awk '{print $3}')
        echo "Stable tag is $stable_tag"
        echo "stable_tag=$stable_tag" >> $GITHUB_ENV

    - name: Create new tag directory
      run: |
        if [ -z "$stable_tag" ]; then
          echo "Stable tag is empty. Please check readme.txt"
          exit 1
        fi
        svn cp svn/trunk svn/tags/$stable_tag --parents --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }} --non-interactive
        svn commit -m "Tagging version $stable_tag" svn/tags/$stable_tag --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }} --non-interactive --no-auth-cache
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        stable_tag: ${{ env.stable_tag }}
